version: '3.9'

# we need to deploy 5 services :)
services:

  # voting app frontend
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - 80:80
    networks:
      - frontend
    deploy:
      replicas: 2
      restart_policy:
        max_attempts: 3
    
  # redis service
  redis:
    image: redis:3.2
    networks:
      - frontend
    depends_on:
      - vote
    deploy:
      restart_policy:
        max_attempts: 3

  # worker service
  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - frontend
      - backend
    depends_on:
      - redis
    deploy:
      restart_policy:
        max_attempts: 3

  # database
  db:
    image: postgres:9.4
    networks:
      - backend
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db-data:/var/lib/postgresql/data
    depends_on:
      - worker
    deploy:
      restart_policy:
        max_attempts: 3

  # result
  result:
    image: bretfisher/examplevotingapp_result
    networks:
      - backend
    expose:
      - 5001:80
    depends_on:
      - db
    deploy:
      restart_policy:
        max_attempts: 3
